# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username\u7528\u6237\u540d')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f\u65e5\u671f')),
                ('password', models.CharField(max_length=255, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('idDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
