# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
