# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_auto_20181226_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
