# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0014_auto_20181226_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0, verbose_name='auth_user\u8868\u7684id')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f\u65e5\u671f')),
                ('nikename', models.CharField(max_length=255, verbose_name='nikename\u7ef0\u53f7')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
